### ISSUE TITLE
Include instructions for compiling against 3.0.x packaged versions from yum repos

### ISSUE THREAD

**Issue by JCCyC** [cavaliercoder/zabbix-module-systemd#15]
Compiling the agent module:

- Download the exact version of the Zabbix sources that correspond to your running version. Mine is 3.0.9, I put it under /root/src
- `yum groupinstall "Development Tools"`
- `yum install dbus-devel libtool gettext autoconf automake`
- `./autogen.sh`
- `./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib64 --with-zabbix=/root/src/zabbix-3.0.9` (omit --libdir switch if 32 bit machine; replace src download path with your own)
- `make && make install`
- `service zabbix-agent restart`
- `pidof zabbix_agentd` to see if it's running properly

Importing template XML into zabbix:

- Edit version tag from 3.2 to 3.0
- Remove empty `<httptests />` tag

**Comment by jangaraj** [comment]
Example template has been downgraded to 2.0 version, so any supported Zabbix version should import it without any problem. Commit https://github.com/cavaliercoder/zabbix-module-systemd/commit/b210bda4f64c642f6edd17d1764b6286d4b521bb.
