### ISSUE TITLE
unsupported module "libzbxsystemd.so" version: 2

### ISSUE THREAD

**Issue by DocMAX** [cavaliercoder/zabbix-module-systemd#16]
Compiled agains 3.x. So why i get this?

`31570:20170721:185959.527 using configuration file: /etc/zabbix/zabbix_agentd.conf
 31570:20170721:185959.535 unsupported module "libzbxsystemd.so" version: 2
 31570:20170721:185959.536 loading modules failed, exiting...
`

**Comment by jangaraj** [comment]
What is your agent version?:
```
zabbix_agentd -V
```

**Comment by DocMAX** [comment]
zabbix_agentd (daemon) (Zabbix) 3.0.10
Revision 70208 14 July 2017, compilation time: Jul 17 2017 07:58:46

Copyright (C) 2017 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

**Comment by jangaraj** [comment]
You need to compile against 3.0 branch and to be 100% sure against 3.0.10 tag. I guess your _3.x_ means 3.2, where module version 2 is used, but your agent is only 3.0, where module version 1 are only available.
```
svn co svn://svn.zabbix.com/tags/3.0.10 /usr/local/src/zabbix-3.0.10 
```

**Comment by DocMAX** [comment]
Thank you, works now. :-)
