### ISSUE TITLE
Arguments to dbus_connection_unref() were incorrect

### ISSUE THREAD

**Issue by srggavrilov** [cavaliercoder/zabbix-module-systemd#17]
#### Environment:
OS: `4.4.0-81-generic #104-Ubuntu SMP x86_64 GNU/Linux`
zabbix-agent: `zabbix_agentd (daemon) (Zabbix) 3.2.7`
libdbus: `libdbus-1-3:amd64 1.10.6-1ubuntu3.3`
zabbix-module-systemd: built from 8d2d52aeaf2e071762972b8ecc098c2ed75f6fd5 against zabbix-3.2.7 sources.

#### Steps to reproduce:
Ask zabbix for a systemd.cgroup.* key.

#### Expected:
No errors/warnings on stderr.

#### Actual:
`arguments to dbus_connection_unref() were incorrect` warning.

#### Example:
```
$ zabbix_agentd -t systemd.cgroup.mem[dbus.service,rss]
systemd.cgroup.mem[dbus.service,rss]          [u|520192]
process 14252: arguments to dbus_connection_unref() were incorrect, assertion "connection != NULL" failed in file ../../dbus/dbus-connection.c line 2821.
This is normally a bug in some application using the D-Bus library.```

**Comment by jangaraj** [comment]
Could you enable `DebugLevel=5` in your Zabbix agent conf, please? Zabbix agent restart and test `systemd.cgroup.mem[dbus.service,rss]` with `zabbix_get`. Then I would like to see Zabbix agent log file content. Thanks.

**Comment by srggavrilov** [comment]
It's in `zbx_unload_modules()`. Here it goes:
```
 23171:20170906:122442.261 Starting Zabbix Agent [gce-quoteserver-ct]. Zabbix 3.2.7 (revision 70298).
 23171:20170906:122442.261 **** Enabled features ****
 23171:20170906:122442.261 IPv6 support:          YES
 23171:20170906:122442.261 TLS support:           YES
 23171:20170906:122442.261 **************************
 23171:20170906:122442.261 using configuration file: /etc/zabbix/zabbix_agentd.conf
 23171:20170906:122442.261 In zbx_load_modules()
 23171:20170906:122442.261 loading module "/etc/zabbix/modules/libzbxsystemd.so"
 23171:20170906:122442.263 [systemd] starting v1.2.0, compiled: Sep  4 2017 15:51:01
 23171:20170906:122442.263 [systemd] in cgroup_dir_detect()
 23171:20170906:122442.263 [systemd] detected cgroup mount directory: /sys/fs/cgroup/
 23171:20170906:122442.263 [systemd] cpu_cgroup is JoinController cpu,cpuacct
 23171:20170906:122442.263 [systemd] set timeout to 30000ms
 23171:20170906:122442.263 cannot find "zbx_module_history_write_cbs()" function in module "libzbxsystemd.so": /etc/zabbix/modules/libzbxsystemd.so: undefined symbol: zbx_module_history_write_cbs
 23171:20170906:122442.263 loaded modules: libzbxsystemd.so
 23171:20170906:122442.263 End of zbx_load_modules():SUCCEED
 23171:20170906:122442.263 In init_collector_data()
 23171:20170906:122442.263 In zbx_dshm_create() proj_id:112 size:0
 23171:20170906:122442.263 End of zbx_dshm_create():SUCCEED shmid:-1
 23171:20170906:122442.263 End of init_collector_data()
 23171:20170906:122442.263 agent #0 started [main process]
 23174:20170906:122442.264 agent #1 started [collector]
 23174:20170906:122442.265 In init_cpu_collector()
 23175:20170906:122442.265 agent #2 started [listener #1]
 23175:20170906:122442.265 In zbx_tls_init_child()
 23174:20170906:122442.265 End of init_cpu_collector():SUCCEED
 23174:20170906:122442.265 __zbx_zbx_setproctitle() title:'collector [processing data]'
 23174:20170906:122442.265 In update_cpustats()
 23174:20170906:122442.265 End of update_cpustats()
 23174:20170906:122442.265 __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
 23176:20170906:122442.265 agent #3 started [listener #2]
 23176:20170906:122442.265 In zbx_tls_init_child()
 23175:20170906:122442.267 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
 23175:20170906:122442.267 End of zbx_tls_init_child()
 23175:20170906:122442.267 __zbx_zbx_setproctitle() title:'listener #1 [waiting for connection]'
 23176:20170906:122442.267 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
 23176:20170906:122442.267 End of zbx_tls_init_child()
 23176:20170906:122442.267 __zbx_zbx_setproctitle() title:'listener #2 [waiting for connection]'
 23177:20170906:122442.267 agent #4 started [listener #3]
 23177:20170906:122442.267 In zbx_tls_init_child()
 23177:20170906:122442.268 OpenSSL library (version OpenSSL 1.0.2g  1 Mar 2016) initialized
 23177:20170906:122442.268 End of zbx_tls_init_child()
 23177:20170906:122442.268 __zbx_zbx_setproctitle() title:'listener #3 [waiting for connection]'
 23174:20170906:122443.265 __zbx_zbx_setproctitle() title:'collector [processing data]'
 23174:20170906:122443.266 In update_cpustats()
 23174:20170906:122443.266 End of update_cpustats()
 23174:20170906:122443.266 __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
 23174:20170906:122444.266 __zbx_zbx_setproctitle() title:'collector [processing data]'
 23177:20170906:122449.266 Requested [systemd.cgroup.mem[dbus.service,rss]]
 23177:20170906:122449.267 [systemd] in cgroup_mem(()
 23177:20170906:122449.267 [systemd] metric source file: /sys/fs/cgroup/memory/system.slice/dbus.service/memory.stat
 23177:20170906:122449.267 [systemd] looking metric rss in memory.stat file
 23177:20170906:122449.267 [systemd] unit: dbus.service; metric: rss; value: 622592
 23177:20170906:122449.267 Sending back [622592]
 23171:20170906:122502.362 Got signal [signal:15(SIGTERM),sender_pid:23183,sender_uid:0,reason:0]. Exiting ...
 23171:20170906:122502.362 zbx_on_exit() called
 23177:20170906:122502.362 Got signal [signal:15(SIGTERM),sender_pid:1,sender_uid:0,reason:0]. Exiting ...
 23176:20170906:122502.363 Got signal [signal:15(SIGTERM),sender_pid:1,sender_uid:0,reason:0]. Exiting ...
 23175:20170906:122502.364 Got signal [signal:15(SIGTERM),sender_pid:1,sender_uid:0,reason:0]. Exiting ...
 23174:20170906:122502.365 Got signal [signal:15(SIGTERM),sender_pid:1,sender_uid:0,reason:0]. Exiting ...
 23171:20170906:122502.367 In zbx_dshm_destroy() shmid:-1
 23171:20170906:122502.367 End of zbx_dshm_destroy():SUCCEED
 23171:20170906:122502.367 In zbx_unload_modules()
process 23171: arguments to dbus_connection_unref() were incorrect, assertion "connection != NULL" failed in file ../../dbus/dbus-connection.c line 2821.
This is normally a bug in some application using the D-Bus library.
 23171:20170906:122502.367 End of zbx_unload_modules()
 23171:20170906:122502.367 Zabbix Agent stopped. Zabbix 3.2.7 (revision 70298).
```

**Comment by jangaraj** [comment]
Thanks. That's a cosmetic issue when Zabbix agent is stopping. `zabbix_agentd -t` starts agent and then it will stop it. You shouldn't see it if you use `zabbix_get` utility for your testing. We will try to solve it.

**Comment by srggavrilov** [comment]
@jangaraj thank you.

**Comment by guoxiangnan** [comment]
When I install and run zabbix 4.0 server ,I encounter a problem, the log is:  Can you tell me how to solve the problem? thanks very much.

47270:20181027:133515.858 One child process died (PID:47292,exitcode/signal:1). Exiting ...
 47270:20181027:133515.858 zbx_on_exit() called
 47273:20181027:133515.858 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47282:20181027:133515.858 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47291:20181027:133515.858 r14     =     7fff4b1364e8 =      140734452950248 =      140734452950248
 47291:20181027:133515.858 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47289:20181027:133515.859 Got signal [signal:11(SIGSEGV),reason:1,refaddr:0x1000000000]. Crashing ...
 47289:20181027:133515.859 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47272:20181027:133515.859 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47276:20181027:133515.859 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47278:20181027:133515.859 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47277:20181027:133515.859 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47275:20181027:133515.860 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47274:20181027:133515.860 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47280:20181027:133515.860 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47281:20181027:133515.860 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47283:20181027:133515.860 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47285:20181027:133515.860 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47287:20181027:133515.861 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47284:20181027:133515.861 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47286:20181027:133515.861 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47297:20181027:133515.862 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47295:20181027:133515.862 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47296:20181027:133515.862 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47294:20181027:133515.862 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47279:20181027:133515.862 7fb396635000-7fb396834000 ---p 00007000 ca:02 2333165                    /usr/local/openIPMI/lib/libOpenIPMIutils.so.0.0.1
 47299:20181027:133515.862 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47300:20181027:133515.863 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47298:20181027:133515.863 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47304:20181027:133515.863 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47301:20181027:133515.863 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47279:20181027:133515.863 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47302:20181027:133515.863 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47303:20181027:133515.863 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47290:20181027:133515.863 7fb395da1000-7fb395da6000 r--p 0006c000 ca:02 1226062                    /usr/local/lib64/libssl.so.1.0.0
 47290:20181027:133515.863 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47293:20181027:133515.864 00845000-00846000 r--p 00245000 ca:02 1603881                            /usr/local/zabbix/sbin/zabbix_server
 47288:20181027:133515.864 18: /usr/local/zabbix/sbin/zabbix_server(zbx_log_fatal_info+0x132) [0x4b56ff]
 47288:20181027:133515.864 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
 47293:20181027:133515.864 Got signal [signal:15(SIGTERM),sender_pid:47270,sender_uid:201,reason:0]. Exiting ...
zabbix_server [47270]: Error waiting for process with PID 47292: [10] No child processes
 47270:20181027:133515.865 In DBconnect() flag:1
 47270:20181027:133515.866 End of DBconnect():0
 47270:20181027:133515.866 In free_database_cache()
 47270:20181027:133515.866 In DCsync_all()
 47270:20181027:133515.866 In sync_history_cache_full() history_num:0

**Comment by wlin-jin** [comment]
when i use zabbix server 3.4.14 i have problem：
32580:20181129:094148.827 Got signal [signal:15(SIGTERM),sender_pid:30231,sender_uid:0,reason:0]. Exiting ...
 32531:20181129:094148.827 Got signal [signal:15(SIGTERM),sender_pid:30231,sender_uid:0,reason:0]. Exiting ...
 32530:20181129:094148.827 Got signal [signal:15(SIGTERM),sender_pid:30231,sender_uid:0,reason:0]. Exiting ...
 32560:20181129:094148.827 Got signal [signal:15(SIGTERM),sender_pid:30231,sender_uid:0,reason:0]. Exiting ...
  1669:20181129:094148.827 Got signal [signal:15(SIGTERM),sender_pid:30231,sender_uid:0,reason:0]. Exiting ...
  1600:20181129:094148.827 Got signal [signal:15(SIGTERM),sender_pid:30231,sender_uid:0,reason:0]. Exiting ...
  1592:20181129:094148.828 Got signal [signal:15(SIGTERM),sender_pid:30231,sender_uid:0,reason:0]. Exiting ...
 30231:20181129:094149.584 In DBconnect() flag:1
 30231:20181129:094149.591 End of DBconnect():0
 30231:20181129:094149.591 In free_database_cache()
 30231:20181129:094149.591 In DCsync_all()
 30231:20181129:094149.591 In DCsync_history() history_num:0
 30231:20181129:094149.594 syncing history data...
 30231:20181129:094149.594 In zbx_flush_correlated_events() events_num:0
 30231:20181129:094149.594 End of zbx_flush_correlated_events() events_num:0
 30231:20181129:094149.594 In zbx_flush_correlated_events() events_num:0
 30231:20181129:094149.594 End of zbx_flush_correlated_events() events_num:0
 30231:20181129:094149.594 syncing history data done
 30231:20181129:094149.594 In DCsync_trends() trends_num:0
 30231:20181129:094149.594 syncing trend data...
 30231:20181129:094149.594 syncing trend data done
 30231:20181129:094149.594 End of DCsync_trends()
 30231:20181129:094149.594 End of DCsync_all()
 30231:20181129:094149.594 End of free_database_cache()
 30231:20181129:094149.595 In free_configuration_cache()
 30231:20181129:094149.595 End of free_configuration_cache()
 30231:20181129:094149.595 In zbx_vc_destroy()
 30231:20181129:094149.595 End of zbx_vc_destroy()
 30231:20181129:094149.595 In free_selfmon_collector() collector:0x7f6e97ada000
 30231:20181129:094149.595 End of free_selfmon_collector()
 30231:20181129:094149.595 In zbx_unload_modules()
 30231:20181129:094149.595 End of zbx_unload_modules()
 30231:20181129:094149.595 Zabbix Server stopped. Zabbix 3.4.14 (revision 84877).
