### ISSUE TITLE
ZBX_NOTSUPPORTED: Unsupported item key

### ISSUE THREAD

**Issue by mitsus** [cavaliercoder/zabbix-module-systemd#18]
Hi, 
I've compiled and installed module. I see the it into /usr/local/lib/zabbix/modules/libzbxsystemd.so.
I changed paramenters info /etc/systemd/systemconf and I reload then zabbix-agent.

If i call (for example) show this error:
`[root@zabbix zabbix-module-systemd]# zabbix_get -s <ip-address> -k systemd[Architecture]
ZBX_NOTSUPPORTED: Unsupported item key.`

Where is my error?

**Comment by jangaraj** [comment]
https://github.com/cavaliercoder/zabbix-module-systemd#debugging:

> Enable DebugLevel=5 in the Zabbix agent config to see systemd module debug output in the zabbix-agent log file.

**Comment by mitsus** [comment]
Below zabbix_agentd.log with DebugLevel=5:
`677:20171003:093932.035 Requested [systemd[Architecture]]
   677:20171003:093932.035 Sending back [ZBX_NOTSUPPORTED: Unsupported item key.]
   677:20171003:093932.035 __zbx_zbx_setproctitle() title:'listener #1 [waiting for connection]'
   680:20171003:093932.303 In send_buffer() host:'10.200.3.19' port:10051 entries:0/100
   680:20171003:093932.303 End of send_buffer():SUCCEED`

**Comment by jangaraj** [comment]
Please provide more log lines. Startup agent log lines are also important.

**Comment by mitsus** [comment]
Ok. This is complete StartUp agent log:
` 1260:20171003:100851.865 Starting Zabbix Agent [broker01]. Zabbix 3.4.2 (revision 72885).
  1260:20171003:100851.865 **** Enabled features ****
  1260:20171003:100851.865 IPv6 support:          YES
  1260:20171003:100851.865 TLS support:           YES
  1260:20171003:100851.865 **************************
  1260:20171003:100851.865 using configuration file: /etc/zabbix/zabbix_agentd.conf
  1260:20171003:100851.865 In zbx_load_modules()
  1260:20171003:100851.865 End of zbx_load_modules():SUCCEED
  1260:20171003:100851.865 In init_collector_data()
  1260:20171003:100851.865 In zbx_dshm_create() size:0
  1260:20171003:100851.865 End of zbx_dshm_create():SUCCEED shmid:-1
  1260:20171003:100851.865 End of init_collector_data()
  1260:20171003:100851.865 agent #0 started [main process]
  1261:20171003:100851.865 agent #1 started [collector]
  1261:20171003:100851.865 In init_cpu_collector()
  1261:20171003:100851.865 End of init_cpu_collector():SUCCEED
  1262:20171003:100851.865 agent #2 started [listener #1]
  1261:20171003:100851.865 __zbx_zbx_setproctitle() title:'collector [processing data]'
  1262:20171003:100851.865 In zbx_tls_init_child()
  1261:20171003:100851.866 In update_cpustats()
  1263:20171003:100851.866 agent #3 started [listener #2]
  1263:20171003:100851.866 In zbx_tls_init_child()
  1264:20171003:100851.866 agent #4 started [listener #3]
  1264:20171003:100851.866 In zbx_tls_init_child()
  1265:20171003:100851.866 agent #5 started [active checks #1]
  1265:20171003:100851.866 In zbx_tls_init_child()
  1261:20171003:100851.866 End of update_cpustats()
  1261:20171003:100851.866 __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
  1262:20171003:100851.867 OpenSSL library (version OpenSSL 1.0.1e-fips 11 Feb 2013) initialized
  1262:20171003:100851.867 End of zbx_tls_init_child()
  1262:20171003:100851.867 __zbx_zbx_setproctitle() title:'listener #1 [waiting for connection]'
  1263:20171003:100851.867 OpenSSL library (version OpenSSL 1.0.1e-fips 11 Feb 2013) initialized
  1263:20171003:100851.867 End of zbx_tls_init_child()
  1263:20171003:100851.867 __zbx_zbx_setproctitle() title:'listener #2 [waiting for connection]'
  1265:20171003:100851.867 OpenSSL library (version OpenSSL 1.0.1e-fips 11 Feb 2013) initialized
  1264:20171003:100851.867 OpenSSL library (version OpenSSL 1.0.1e-fips 11 Feb 2013) initialized
  1265:20171003:100851.868 End of zbx_tls_init_child()
  1265:20171003:100851.868 In init_active_metrics()
  1265:20171003:100851.868 buffer: first allocation for 100 elements
  1264:20171003:100851.868 End of zbx_tls_init_child()
  1265:20171003:100851.868 End of init_active_metrics()
  1264:20171003:100851.868 __zbx_zbx_setproctitle() title:'listener #3 [waiting for connection]'
  1265:20171003:100851.868 In send_buffer() host:'10.200.3.19' port:10051 entries:0/100
  1265:20171003:100851.868 End of send_buffer():SUCCEED
  1265:20171003:100851.868 __zbx_zbx_setproctitle() title:'active checks #1 [getting list of active checks]'
  1265:20171003:100851.868 In refresh_active_checks() host:'10.200.3.19' port:10051
  1265:20171003:100851.868 sending [{"request":"active checks","host":"broker01","ip":"0.0.0.0"}]
  1265:20171003:100851.868 before read
  1265:20171003:100851.869 got [{"response":"success","data":[]}]
  1265:20171003:100851.869 In parse_list_of_checks()
  1265:20171003:100851.870 End of parse_list_of_checks():SUCCEED
  1265:20171003:100851.870 End of refresh_active_checks():SUCCEED`

**Comment by jangaraj** [comment]
Your agent is not configured to load systemd module. Please configure it: https://www.zabbix.com/documentation/3.4/manual/config/items/loadablemodules

**Comment by mitsus** [comment]
You have right. Sorry. I added LoadModule and LoadModulePath...adn it work now. Thanks ;)
