### ISSUE TITLE
Monitoring an custom systemctl process

### ISSUE THREAD

**Issue by mitsus** [cavaliercoder/zabbix-module-systemd#19]
Hi, 
how can I monitor an custom systemctl process?
For example i run a service (java process with parameters) with the command: 
`systemctl start broker`.
It run as:
`java -server -Xms24g -Xmx24g -XX:MaxDirectMemorySize=56g -XX:+UseG1GC -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=75....`

Thanks

**Comment by jangaraj** [comment]
Sorry, that's a request for a support, it's not an issue.

**Comment by cavaliercoder** [comment]
You're probably looking for `systemd.service.info`. Please see the readme.
