### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by jangaraj** [cavaliercoder/zabbix-module-systemd#2]
Thanks Ryan for publishing your systemd module 👍 . I made similar one based on [sd-bus API of systemd](http://0pointer.net/blog/the-new-sd-bus-api-of-systemd.html) a few months ago, but I didn't publish it. There is published only [cgroup version](https://github.com/monitoringartist/zabbix-systemd-monitoring) as a part of docker module. I would like to deprecate my systemd monitoring in favor of your systemd module. I would like to see these features:

- Filter unit type in unit discovery
It will simplify creating of LLD rules per unittype. `systemd.unit.discovery[<unittype>]` - type of discovered unit: service, socket, device, mount, automount, ... Default value probably: all.

- Cgroup resource monitoring
For example systemd services are "containers", so you can read their CPU/mem/IOPs metrics from the cgroups
`systemd.cgroup.mem[fid,mmetric], systemd.cgroup.cpu[fid,cmetric], systemd.cgroup.dev[fid,bfile,bmetric] ,...`

**Comment by cavaliercoder** [comment]
Nice one! Yep I agree with these ideas. I'm also happy if you want to submit PRs for these features.

**Comment by jangaraj** [comment]
I'll try to create PR for `systemd.cgroup.*`.

**Comment by jangaraj** [comment]
Fixed by #3.  https://github.com/monitoringartist/zabbix-systemd-monitoring is deprecated in favor of this project as well.
