### ISSUE TITLE
Cannot use for zabbix agent version for 3.0 or less than that.

### ISSUE THREAD

**Issue by mayekarsupriya** [cavaliercoder/zabbix-module-systemd#27]
#rpm -ivh zabbix-module-systemd-1.2.0-1.x86_64.rpm
error: Failed dependencies:
        zabbix-agent >= 3.2.0 is needed by zabbix-module-systemd-1.2.0-1.x86_64

**Comment by cavaliercoder** [comment]
You can compile this module to work with any version of Zabbix.

Currently, there is no plan to provide RPM packages for older versions of Zabbix. This requires a huge amount of effort :(
