### ISSUE TITLE
[systemd] failed to get d-bus session:

### ISSUE THREAD

**Issue by dragan1979** [cavaliercoder/zabbix-module-systemd#31]
output from zabbix agent

 `[systemd] failed to get d-bus session: Failed to connect to socket /run/dbus/system_bus_socket: Permission denied`

**Comment by jangaraj** [comment]
Please provide agent logs - https://github.com/cavaliercoder/zabbix-module-systemd#debugging
and your SELinux configuration - https://github.com/cavaliercoder/zabbix-module-systemd#selinux.

**Comment by dragan1979** [comment]
I disabled SELinux and then got processes in zabbix, only for 6 services getting exclamation mark (Cannot open cpuacct.stat file/Cannot open memory.stat file) under monitor-latest data

[```
systemd] cannot open metric file: '/sys/fs/cgroup/memory/system.slice/irqbalance.service/memory.stat'
 14852:20180821:220840.725 [systemd] cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/system.slice/kdump.service/cpuacct.stat'
 14853:20180821:220844.007 [systemd] cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/system.slice/irqbalance.service/cpuacct.stat'
 14853:20180821:220851.309 [systemd] cannot open metric file: '/sys/fs/cgroup/memory/system.slice/getty@tty1.service/memory.stat'
 14852:20180821:221802.714 [systemd] cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/system.slice/getty@tty1.service/cpuacct.stat'
 14853:20180821:221810.083 [systemd] cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/system.slice/kdump.service/cpuacct.stat'
 14854:20180821:221814.101 [systemd] cannot open metric file: '/sys/fs/cgroup/cpu,cpuacct/system.slice/irqbalance.service/cpuacct.stat'
 14854:20180821:221821.358 [systemd] cannot open metric file: '/sys/fs/cgroup/memory/system.slice/getty@tty1.service/memory.stat'
 14852:20180821:221829.482 [systemd] cannot open metric file: '/sys/fs/cgroup/memory/system.slice/kdump.service/memory.stat'
 14854:20180821:221833.588 [systemd] cannot open metric file: '/sys/fs/cgroup/memory/system.slice/irqbalance.service/memory.stat'
```

**Comment by jangaraj** [comment]
See: https://github.com/cavaliercoder/zabbix-module-systemd/issues/12

**Comment by dragan1979** [comment]
sorry, don't follow, all above files doesn't exist on my system, not sure what should i do to get rid of above message-to disable those items ?

**Comment by jangaraj** [comment]
See https://github.com/cavaliercoder/zabbix-module-systemd/issues/12 => that's already reported issue. If you want to resolve it, then you need to.make your hand dirty, because this issue is still not resolved => you will need to code it or wait for resolution provided by someone else.

**Comment by dragan1979** [comment]
ok, thanks,last question:
in systems where SELinux is ON
how to add exception to get rid of 

`[systemd] failed to get d-bus session: Failed to connect to socket /run/dbus/system_bus_socket: Permission denied`

**Comment by dragan1979** [comment]
stupid me, sorry didn't see SELinux link, will try and open new issue if face errors, thanks a lot for this template !!
