### ISSUE TITLE
Monitoring Template Systemd Units

### ISSUE THREAD

**Issue by fxfitz** [cavaliercoder/zabbix-module-systemd#35]
How does monitor a templated systemd unit? For example, here's the ClamAV service:

<img width="1330" alt="Screen Shot 2019-06-13 at 10 56 47 AM" src="https://user-images.githubusercontent.com/6355826/59448065-06e39880-8dca-11e9-9c96-7a67e804d079.png">

Since Zabbix doesn't like `@` in the fields, how does this work?

Reference for templated unit files: https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files

Then scroll to the "Creating Instance Units from Template Unit Files" part.

**Comment by jangaraj** [comment]
Could you update template and try to use quotes for parameter - e.g. `systemd.service.status["clamd@scan]`?

https://www.zabbix.com/documentation/4.2/manual/config/items/item/key

> If the key parameter is a quoted string, any Unicode character is allowed, and included double quotes must be backslash escaped.

**Comment by i-ky** [comment]
This error message comes from [Zabbix UserParameter processing code](https://github.com/zabbix/zabbix/blob/86e41ec878b740666af51e0c04adb5b1541e3a4e/src/libs/zbxsysinfo/sysinfo.c#L486):
```c
		zbx_snprintf(error, max_error_len, "Special characters \"%s\" are not allowed in the parameters.", buf);
```
Perhaps, you have to enable `UnsafeUserParameters` in agent's configuration file.

**Comment by jangaraj** [comment]
Yes, you need that.

**Comment by fxfitz** [comment]
Well, TIL about `UnsafeUserParameters`. That has fixed it!

Thank you all so much for the help.

**Comment by cwhel** [comment]
We're having an issue with services with a number after the @ symbol not being discovered correctly... For example, we have a service called sensor@0... Zabbix is only picking up the sensor@ portion and not able to correctly collect data for that service... any ideas?

**Comment by cwhel** [comment]
but our clamav@scan picks up just fine

**Comment by jangaraj** [comment]
Use zabbix_get and check what is returned from zabbix agent for discovery item. Maybe module doesn't return correct value.

**Comment by cwhel** [comment]
the agent isn't discovering the service correctly... but I can do a zabbix_get on the correct service to get the value I need... I'm not sure how to get the agent to discover the entire service name of "sensor@0"

the item key looks like this: systemd.service.status[sensor@]

zabbix_get -s <server> -k systemd.service.status[sensor@]                       
1
zabbix_get -s <server> -k systemd.service.status[sensor@0]
0

**Comment by cwhel** [comment]
We actually just found an error in how we're doing discovery and were able to resolve the issue... thanks!
