### ISSUE TITLE
configure: error: /usr/src/zabbix/include/module.h does not exist

### ISSUE THREAD

**Issue by abctechs** [cavaliercoder/zabbix-module-systemd#36]
I need to "svn export svn://svn.zabbix.com/tags/4.0.11 /usr/src/zabbix", but this doesn't work.
svn package is no longer available.
I also found that svn was moved to git.

Do you have an idea what that updated command would be?

Thank you!

**Comment by i-ky** [comment]
Something like:
```bash
$ git clone https://git.zabbix.com/scm/zbx/zabbix.git --depth 1 --single-branch --branch 4.0.11 /usr/src/zabbix
```

**Comment by jangaraj** [comment]
Thx. Readme updated.

**Comment by abctechs** [comment]
That works thanks.
How do I load the module into zabbix? I cannot figure this out and I haven't done that before. And when trying to do the debugging, the gdbus app on ubuntu does not exists anymore. 
I imported the template and added the template to the host, and the discovery of services is not working. It looks like I am missing something, which most likely is the module.
thanks for your help

**Comment by jangaraj** [comment]
Check readme, pls. There is a link https://www.zabbix.com/documentation/3.4/manual/config/items/loadablemodules see section "13.3.17 Configuration parameters"

**Comment by abctechs** [comment]
Thank you for your help on this one.
I have loaded the module. Thanks for the guide. I didn't see that. According to the Zabbix log file the module is loaded. But apparently there is an issue with the module. Module cannot find "zbx_module_history_write_cbs()" function.
Log Below

```
 45461:20190903:204420.424 Starting Zabbix Agent [hge-zabbix01-proxy]. Zabbix 4.0.11 (revision 53bb6bc0f0).
 45461:20190903:204420.424 **** Enabled features ****
 45461:20190903:204420.424 IPv6 support:          YES
 45461:20190903:204420.424 TLS support:           YES
 45461:20190903:204420.424 **************************
 45461:20190903:204420.424 using configuration file: /etc/zabbix/zabbix_agentd.conf
 45461:20190903:204420.424 In zbx_load_modules()
 45461:20190903:204420.425 loading module "**/usr/local/lib/zabbix/modules/libzbxsystemd.so**"
 45461:20190903:204420.428 [systemd] starting v1.2.0, compiled: Aug 28 2019 22:47:17
 45461:20190903:204420.428 [systemd] in cgroup_dir_detect()
 45461:20190903:204420.428 [systemd] detected cgroup mount directory: /sys/fs/cgroup/
 45461:20190903:204420.428 [systemd] cpu_cgroup is JoinController cpu,cpuacct
 45461:20190903:204420.428 [systemd] set timeout to 3000ms
 **45461:20190903:204420.428 cannot find "zbx_module_history_write_cbs()" function in module "libzbxsystemd.so": /usr/local/lib/zabbix/modules/libzbxsystemd.so: undefined symbol: zbx_module_history_write_cbs**
 45461:20190903:204420.429 loaded modules: libzbxsystemd.so
 45461:20190903:204420.429 End of zbx_load_modules():SUCCEED
```

Also when I type a command `zabbix_get -s 127.0.0.1 -k systemd[Architecture]` I get below results.
ZBX_NOTSUPPORTED: Failed to connect to D-Bus.

And Zabbix log file alerts
```
 45463:20190903:204717.297 [systemd] failed to get d-bus session: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
 45463:20190903:204717.297 Sending back [ZBX_NOTSUPPORTED: Failed to connect to D-Bus.]
```

System Info:
`zabbix_agentd -V`
zabbix_agentd (daemon) (Zabbix) 4.0.11
Compiled with OpenSSL 1.0.2g-fips  1 Mar 2016
Running with OpenSSL 1.0.2g  1 Mar 2016
`uname -a`
Linux proxy-hge-zabbix01 4.4.0-159-generic #187-Ubuntu SMP Thu Aug 1 16:28:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Do you have any suggestions for this type of issue?

Thank you!

**Comment by jangaraj** [comment]
```
failed to get d-bus session: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
```
Do you really have a system with systemd? https://github.com/cavaliercoder/zabbix-module-systemd#debugging

**Comment by abctechs** [comment]
I think so.
systemd services are installed.

```
apt list | grep systemd
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
click-systemd/xenial,xenial 0.2 all
dh-systemd/xenial-updates,xenial-updates 1.29ubuntu4 all
golang-github-coreos-go-systemd-dev/xenial,xenial 3-2 all
kde-config-systemd/xenial 1.2.1-3ubuntu1 amd64
libpam-systemd/xenial-updates 229-4ubuntu21.22 amd64
libsystemd-dev/xenial-updates 229-4ubuntu21.22 amd64
libsystemd0/xenial-updates,now 229-4ubuntu21.22 amd64 [installed]
python-systemd/xenial 231-2build1 amd64
python3-systemd/xenial 231-2build1 amd64
systemd/xenial-updates,now 229-4ubuntu21.22 amd64 [installed]
systemd-container/xenial-updates 229-4ubuntu21.22 amd64
systemd-coredump/xenial-updates 229-4ubuntu21.22 amd64
systemd-cron/xenial,xenial 1.5.3-1 all
systemd-dbg/xenial-updates 229-4ubuntu21.22 amd64
systemd-docker/xenial 0.2.1+dfsg-1 amd64
systemd-gui/xenial,xenial 1:3-4 all
systemd-journal-remote/xenial-updates 229-4ubuntu21.22 amd64
systemd-shim/xenial 9-1bzr4ubuntu1 amd64
systemd-sysv/xenial-updates,now 229-4ubuntu21.22 amd64 [installed]
systemd-ui/xenial 3-4 amd64
```
