### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by masikmos** [cavaliercoder/zabbix-module-systemd#38]
Zabbix 4.2.6 module work fine but got spam in log file

property: ActiveState 6678:20190930:015629.347 [systemd] getting property: service: org.freedesktop.systemd1 object path: /org/freedesktop/systemd1/unit/systemd_2dnetworkd_2dwait_2donline_2eservice interface: org.freedesktop.systemd1.Unit property: ActiveState 6678:20190930:015629.395 [systemd] in cgroup_cpu() 6678:20190930:015629.395 [systemd] metric source file: /sys/fs/cgroup/cpu,cpuacct/system.slice/networkd-dispatcher.service/cpuacct.stat 6678:20190930:015629.395 [systemd] looking metric total in cpuacct.stat/cpu.stat file 6678:20190930:015629.395 [systemd] unit: networkd-dispatcher.service; metric: total; value: 2 6679:20190930:015630.493 [systemd] in cgroup_cpu() 6679:20190930:015630.493 [systemd] metric source file: /sys/fs/cgroup/cpu,cpuacct/system.slice/elasticsearch.service/cpuacct.stat 6679:20190930:015630.493 [systemd] looking metric total in cpuacct.stat/cpu.stat file 6679:20190930:015630.493 [systemd] unit: elasticsearch.service; metric: total; value: 10613 6679:20190930:015630.534 [systemd] in cgroup_mem(() 6679:20190930:015630.534 [systemd] metric source file: /sys/fs/cgroup/memory/system.slice/zabbix-agent.service/memory.stat 6679:20190930:015630.535 [systemd] looking metric total_rss in memory.stat file 6679:20190930:015630.535 [systemd] unit: zabbix-agent.service; metric: total_rss; value: 3694592 6680:20190930:015630.536 [systemd] getting property: service: org.freedesktop.systemd1 object path: /org/freedesktop/systemd1/unit/vgauth_2eservice interface: org.freedesktop.systemd1.Unit property: ActiveState 6678:20190930:015630.565 [systemd] getting property: service: org.freedesktop.systemd1 object path: /org/freedesktop/systemd1/unit/rsyslog_2eservice interface: org.freedesktop.systemd1.Unit property: ActiveState

Help disable it please...

Why issue closed? problem not fixed

i set debug level 0 and still see spam

**Comment by masikmos** [comment]
how to disabled all logs in SRC for this module?
i dont know CPP\C...

**Comment by jangaraj** [comment]
Closing this one. Please don't open new one. You, already have #37, so please keep only one issue.

**Comment by masikmos** [comment]
But you closed my issue.....

**Comment by jangaraj** [comment]
Yes, but you can comment also closed issue. I'm locking this issue.
