### ISSUE TITLE
Cannot download source package

### ISSUE THREAD

**Issue by banzayats** [cavaliercoder/zabbix-module-systemd#4]
While trying to download packages using the provided link http://s3.cavaliercoder.com/zabbix-contrib/release/zabbix-module-systemd-1.2.0.tar.gz I see the following error page:
```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>54D7F9ECB02117F3</RequestId>
  <HostId>
    KelepDF0sW89FQXR/twBE1q7blfHMyTZ+8lKY3/zKsr9/Y8AR4JWAnrZvGOL1MxJNe85o0h/PYo=
  </HostId>
</Error>
```

**Comment by cavaliercoder** [comment]
Thanks for reporting this. I've fixed the incorrect URLs. Please try again now :)
